import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useCreateUser, useUpdateUser } from '../hooks/use-user';
import { Permission } from '../lib/permissions';
import { useAuth } from '../hooks/use-auth';
import { UserModuleTypes } from '@/lib/api';

// GENERATED CODE - DO NOT MODIFY
// This file was generated by the FormBuilder.

const schema = z.object({
  username: z.string().optional(),
  email: z.string().email().optional(),
  passwordUpdatedAt: z.coerce.date().optional(),
  emailVerified: z.coerce.date().optional(),
  name: z.string().optional(),
  image: z.string().optional(),
  role: z.nativeEnum(UserModuleTypes.SiteRole).optional(),
  status: z.nativeEnum(UserModuleTypes.UserStatus).optional(),
});

type FormData = z.infer<typeof schema>;

export function UserForm({
  id,
  initialData,
  onSuccess,
}: {
  id?: string;
  initialData?: Partial<FormData>;
  onSuccess?: () => void;
}) {
  const { t } = useTranslation();
  const isEdit = !!id,
    createMutation = useCreateUser(),
    updateMutation = useUpdateUser(id);
  const { user } = useAuth();
  const canCreate = Permission.check('user:create', user?.role || 'ANONYMOUS'),
    canUpdate = Permission.check('user:update', user?.role || 'ANONYMOUS');

  /* eslint-disable @typescript-eslint/no-explicit-any */
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<any>({
    resolver: zodResolver(schema),
    defaultValues: initialData || {},
  });

  useEffect(() => {
    if (initialData) {
      reset(initialData);
    }
  }, [initialData, reset]);

  const onSubmit = (data: FormData) => {
    if (isEdit && id) {
      updateMutation.mutate(data, { onSuccess });
    } else {
      createMutation.mutate(data, { onSuccess });
    }
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4 form-container">
      <div className="form-group space-y-group">
        <label htmlFor="username" className="input-label">
          {t('module.user.field.username')}
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="username"
            {...register('username')}
            className="input-field w-full"
          />
        </div>
        {errors.username && (
          <p className="feedback-error-text mt-2">{errors.username?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="email" className="input-label">
          {t('module.user.field.email')}
        </label>
        <div className="mt-1">
          <input type="text" id="email" {...register('email')} className="input-field w-full" />
        </div>
        {errors.email && (
          <p className="feedback-error-text mt-2">{errors.email?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="passwordUpdatedAt" className="input-label">
          {t('module.user.field.passwordUpdatedAt')}
        </label>
        <div className="mt-1">
          <input
            type="datetime-local"
            id="passwordUpdatedAt"
            {...register('passwordUpdatedAt')}
            className="input-field w-full"
          />
        </div>
        {errors.passwordUpdatedAt && (
          <p className="feedback-error-text mt-2">{errors.passwordUpdatedAt?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="emailVerified" className="input-label">
          {t('module.user.field.emailVerified')}
        </label>
        <div className="mt-1">
          <input
            type="datetime-local"
            id="emailVerified"
            {...register('emailVerified')}
            className="input-field w-full"
          />
        </div>
        {errors.emailVerified && (
          <p className="feedback-error-text mt-2">{errors.emailVerified?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="name" className="input-label">
          {t('module.user.field.name')}
        </label>
        <div className="mt-1">
          <input type="text" id="name" {...register('name')} className="input-field w-full" />
        </div>
        {errors.name && (
          <p className="feedback-error-text mt-2">{errors.name?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="image" className="input-label">
          {t('module.user.field.image')}
        </label>
        <div className="mt-1">
          <input type="text" id="image" {...register('image')} className="input-field w-full" />
        </div>
        {errors.image && (
          <p className="feedback-error-text mt-2">{errors.image?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="role" className="input-label">
          {t('module.user.field.role')}
        </label>
        <div className="mt-1">
          <input type="text" id="role" {...register('role')} className="input-field w-full" />
        </div>
        {errors.role && (
          <p className="feedback-error-text mt-2">{errors.role?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="status" className="input-label">
          {t('module.user.field.status')}
        </label>
        <div className="mt-1">
          <input type="text" id="status" {...register('status')} className="input-field w-full" />
        </div>
        {errors.status && (
          <p className="feedback-error-text mt-2">{errors.status?.message as string}</p>
        )}
      </div>
      {(isEdit ? canUpdate : canCreate) && (
        <button
          type="submit"
          disabled={isSubmitting}
          className="btn-primary btn-dims-default w-full sm:w-auto"
        >
          {isSubmitting
            ? t('common.status.saving')
            : isEdit
              ? t('common.actions.update')
              : t('common.actions.create')}
        </button>
      )}
    </form>
  );
}
