import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useCreateUser, useUpdateUser } from '../hooks/use-user';
import { UserModuleTypes } from '@/lib/api';
import { Permission } from '../lib/permissions';
import { useNavData } from '@/lib/ui/nav-context';
import { PasswordInput } from '@/components/ui/password-input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

// GENERATED CODE - DO NOT MODIFY
// This file was generated by the FormBuilder.
export function UserForm({
  id,
  initialData,
  onSuccess,
}: {
  id?: string;
  initialData?: UserModuleTypes.User;
  onSuccess?: () => void;
}) {
  const { t } = useTranslation();
  const isEdit = !!id,
    createMutation = useCreateUser(),
    updateMutation = useUpdateUser();
  const { context } = useNavData(),
    user = context?.user,
    SiteRole = UserModuleTypes.SiteRole,
    UserStatus = UserModuleTypes.UserStatus;
  const canCreate = Permission.check('user:create', user?.role || 'ANONYMOUS'),
    canUpdate = Permission.check('user:update', user?.role || 'ANONYMOUS');
  const schema = z.object({
    username: z.string().optional(),
    email: z.string().email().optional(),
    password: z.string().optional(),
    name: z.string().optional(),
    image: z.string().optional(),
    role: z.nativeEnum(SiteRole).optional(),
    status: z.nativeEnum(UserStatus).optional(),
  });
  type FormData = z.infer<typeof schema>;
  const {
    register,
    handleSubmit,
    reset,
    control,
    formState: { errors, isSubmitting },
  } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: (initialData as unknown as FormData) || {},
  });
  useEffect(() => {
    if (initialData) {
      reset(initialData as unknown as FormData);
    }
  }, [initialData, reset]);
  const onSubmit = (data: FormData) => {
    if (isEdit && id) {
      updateMutation.mutate(
        { id, data: data as unknown as UserModuleTypes.UpdateUserDTO },
        { onSuccess },
      );
    } else {
      createMutation.mutate(data as unknown as UserModuleTypes.CreateUserDTO, { onSuccess });
    }
  };
  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4 form-container">
      <div className="form-group space-y-group">
        <label htmlFor="username" className="input-label">
          {t('module.user.field.username')}
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="username"
            {...register('username')}
            className="input-field w-full"
          />
        </div>
        {errors.username && (
          <p className="feedback-error-text mt-2">{errors.username?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="email" className="input-label">
          {t('module.user.field.email')}
        </label>
        <div className="mt-1">
          <input type="text" id="email" {...register('email')} className="input-field w-full" />
        </div>
        {errors.email && (
          <p className="feedback-error-text mt-2">{errors.email?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="password" className="input-label">
          {t('module.user.field.password')}
        </label>
        <div className="mt-1">
          <PasswordInput id="password" {...register('password')} />
        </div>
        {errors.password && (
          <p className="feedback-error-text mt-2">{errors.password?.message as string}</p>
        )}
      </div>

      <div className="form-group space-y-group">
        <label htmlFor="name" className="input-label">
          {t('module.user.field.name')}
        </label>
        <div className="mt-1">
          <input type="text" id="name" {...register('name')} className="input-field w-full" />
        </div>
        {errors.name && (
          <p className="feedback-error-text mt-2">{errors.name?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="image" className="input-label">
          {t('module.user.field.image')}
        </label>
        <div className="mt-1">
          <input type="text" id="image" {...register('image')} className="input-field w-full" />
        </div>
        {errors.image && (
          <p className="feedback-error-text mt-2">{errors.image?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="role" className="input-label">
          {t('module.user.field.role')}
        </label>
        <div className="mt-1">
          <Controller
            name="role"
            control={control}
            render={({ field }) => (
              <Select onValueChange={field.onChange} defaultValue={field.value}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder={t('module.user.field.role')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ADMIN">{t('UserModuleTypes.SiteRole.ADMIN')}</SelectItem>
                  <SelectItem value="EMPLOYEE">{t('UserModuleTypes.SiteRole.EMPLOYEE')}</SelectItem>
                  <SelectItem value="CONTRACTOR">
                    {t('UserModuleTypes.SiteRole.CONTRACTOR')}
                  </SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>
        {errors.role && (
          <p className="feedback-error-text mt-2">{errors.role?.message as string}</p>
        )}
      </div>
      <div className="form-group space-y-group">
        <label htmlFor="status" className="input-label">
          {t('module.user.field.status')}
        </label>
        <div className="mt-1">
          <Controller
            name="status"
            control={control}
            render={({ field }) => (
              <Select onValueChange={field.onChange} defaultValue={field.value}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder={t('module.user.field.status')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ACTIVE">{t('UserModuleTypes.UserStatus.ACTIVE')}</SelectItem>
                  <SelectItem value="INACTIVE">
                    {t('UserModuleTypes.UserStatus.INACTIVE')}
                  </SelectItem>
                  <SelectItem value="BANNED">{t('UserModuleTypes.UserStatus.BANNED')}</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>
        {errors.status && (
          <p className="feedback-error-text mt-2">{errors.status?.message as string}</p>
        )}
      </div>
      {(isEdit ? canUpdate : canCreate) && (
        <button
          type="submit"
          disabled={isSubmitting}
          className="btn-primary btn-dims-default w-full sm:w-auto"
        >
          {isSubmitting
            ? t('common.status.saving')
            : isEdit
              ? t('common.actions.update')
              : t('common.actions.create')}
        </button>
      )}
    </form>
  );
}
